# Use the official golang:alpine image as the base image
FROM golang:alpine

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Build the Go app
RUN go build -o main . && limit=30

# Expose port 8080 for the application
EXPOSE 8080

# Run the Go app when the container starts
CMD ["./main"]
